// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type WatchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceId      string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	CurrentVersion int32                  `protobuf:"varint,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_api_proto_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{1}
}

func (x *WatchRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *WatchRequest) GetCurrentVersion() int32 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,3,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_proto_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *UpdateRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_api_proto_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{3}
}

func (x *Config) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Config) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Config) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_api_proto_config_proto protoreflect.FileDescriptor

const file_api_proto_config_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/config.proto\x12\x06config\"+\n" +
	"\n" +
	"GetRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"V\n" +
	"\fWatchRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\x05R\x0ecurrentVersion\"a\n" +
	"\rUpdateRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x03 \x01(\tR\tupdatedBy\"U\n" +
	"\x06Config\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion2\xae\x01\n" +
	"\rConfigService\x12/\n" +
	"\tGetConfig\x12\x12.config.GetRequest\x1a\x0e.config.Config\x125\n" +
	"\vWatchConfig\x12\x14.config.WatchRequest\x1a\x0e.config.Config0\x01\x125\n" +
	"\fUpdateConfig\x12\x15.config.UpdateRequest\x1a\x0e.config.ConfigB\x10Z\x0emain/api/protob\x06proto3"

var (
	file_api_proto_config_proto_rawDescOnce sync.Once
	file_api_proto_config_proto_rawDescData []byte
)

func file_api_proto_config_proto_rawDescGZIP() []byte {
	file_api_proto_config_proto_rawDescOnce.Do(func() {
		file_api_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_config_proto_rawDesc), len(file_api_proto_config_proto_rawDesc)))
	})
	return file_api_proto_config_proto_rawDescData
}

var file_api_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_config_proto_goTypes = []any{
	(*GetRequest)(nil),    // 0: config.GetRequest
	(*WatchRequest)(nil),  // 1: config.WatchRequest
	(*UpdateRequest)(nil), // 2: config.UpdateRequest
	(*Config)(nil),        // 3: config.Config
}
var file_api_proto_config_proto_depIdxs = []int32{
	0, // 0: config.ConfigService.GetConfig:input_type -> config.GetRequest
	1, // 1: config.ConfigService.WatchConfig:input_type -> config.WatchRequest
	2, // 2: config.ConfigService.UpdateConfig:input_type -> config.UpdateRequest
	3, // 3: config.ConfigService.GetConfig:output_type -> config.Config
	3, // 4: config.ConfigService.WatchConfig:output_type -> config.Config
	3, // 5: config.ConfigService.UpdateConfig:output_type -> config.Config
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_config_proto_init() }
func file_api_proto_config_proto_init() {
	if File_api_proto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_config_proto_rawDesc), len(file_api_proto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_config_proto_goTypes,
		DependencyIndexes: file_api_proto_config_proto_depIdxs,
		MessageInfos:      file_api_proto_config_proto_msgTypes,
	}.Build()
	File_api_proto_config_proto = out.File
	file_api_proto_config_proto_goTypes = nil
	file_api_proto_config_proto_depIdxs = nil
}
