// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/config/{service_id}": {
            "get": {
                "description": "Возвращает список всех версий конфигурации для указанного сервиса с пагинацией. Версии отсортированы по убыванию (новые сверху).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "Получение списка версий конфигурации",
                "parameters": [
                    {
                        "type": "string",
                        "example": "user-service",
                        "description": "ID сервиса",
                        "name": "service_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "example": 20,
                        "description": "Количество записей на страницу (макс. 100, по умолчанию 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "example": 0,
                        "description": "Смещение для пагинации",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список версий конфигурации",
                        "schema": {
                            "$ref": "#/definitions/configHandler.ConfigListResponse"
                        }
                    },
                    "400": {
                        "description": "service_id is required",
                        "schema": {
                            "$ref": "#/definitions/configHandler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/configHandler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новую конфигурацию для указанного сервиса. Конфигурация загружается в виде JSON файла через multipart/form-data.\nФайл должен содержать валидный JSON. После успешного создания автоматически инкрементируется версия конфигурации.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "Создание новой конфигурации",
                "parameters": [
                    {
                        "type": "string",
                        "example": "user-service",
                        "description": "ID сервиса",
                        "name": "service_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "JSON файл с конфигурацией (макс. 5MB)",
                        "name": "config",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Конфигурация успешно создана",
                        "schema": {
                            "$ref": "#/definitions/configHandler.CreateConfigResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос: отсутствует service_id, файл слишком большой, неверный формат или невалидный JSON",
                        "schema": {
                            "$ref": "#/definitions/configHandler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/configHandler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/config/{service_id}/actual": {
            "get": {
                "description": "Возвращает последнюю (актуальную) версию конфигурации для указанного сервиса. Включает данные конфигурации и метаинформацию.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "Получение актуальной конфигурации сервиса",
                "parameters": [
                    {
                        "type": "string",
                        "example": "user-service",
                        "description": "ID сервиса",
                        "name": "service_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Актуальная конфигурация сервиса",
                        "schema": {
                            "$ref": "#/definitions/configHandler.ConfigResponse"
                        }
                    },
                    "400": {
                        "description": "service_id is required",
                        "schema": {
                            "$ref": "#/definitions/configHandler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Конфигурация для указанного сервиса не найдена",
                        "schema": {
                            "$ref": "#/definitions/configHandler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/configHandler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/config/{service_id}/{version}": {
            "get": {
                "description": "Возвращает конфигурацию указанной версии для сервиса. Версии нумеруются с 1 (самая старая) до N (самая новая).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "Получение конкретной версии конфигурации",
                "parameters": [
                    {
                        "type": "string",
                        "example": "user-service",
                        "description": "ID сервиса",
                        "name": "service_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "example": 3,
                        "description": "Номер версии конфигурации",
                        "name": "version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Конфигурация указанной версии",
                        "schema": {
                            "$ref": "#/definitions/configHandler.ConfigVersionResponse"
                        }
                    },
                    "400": {
                        "description": "service_id is required | version must be integer",
                        "schema": {
                            "$ref": "#/definitions/configHandler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Конфигурация с указанной версией не найдена",
                        "schema": {
                            "$ref": "#/definitions/configHandler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/configHandler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/config/{service_id}/{version}/rollback": {
            "post": {
                "description": "Выполняет откат конфигурации сервиса к указанной версии. Создается новая версия с данными из целевой версии.\nВерсия автоматически инкрементируется. Watcher получит уведомление об изменении.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "Откат конфигурации к указанной версии",
                "parameters": [
                    {
                        "type": "string",
                        "example": "user-service",
                        "description": "ID сервиса",
                        "name": "service_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "example": 3,
                        "description": "Номер версии для отката",
                        "name": "version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный откат конфигурации",
                        "schema": {
                            "$ref": "#/definitions/configHandler.RollbackResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос: отсутствует service_id или target_version",
                        "schema": {
                            "$ref": "#/definitions/configHandler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Сервис не найден или указанная версия не существует",
                        "schema": {
                            "$ref": "#/definitions/configHandler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Невозможно выполнить откат (например, уже на этой версии)",
                        "schema": {
                            "$ref": "#/definitions/configHandler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/configHandler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/schema/{service_id}": {
            "get": {
                "description": "Возвращает JSON-схему для указанного сервиса по его ID. Схема используется для валидации конфигураций сервиса.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schemas"
                ],
                "summary": "Получение схемы сервиса",
                "parameters": [
                    {
                        "type": "string",
                        "example": "user-service",
                        "description": "Уникальный идентификатор сервиса",
                        "name": "service_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "JSON-схема сервиса",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "service_id is required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "схема с указанным service_id не найдена",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет JSON-схему для указанного сервиса по его ID. В случае успеха возвращает информацию об удаленном сервисе.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schemas"
                ],
                "summary": "Удаление схемы сервиса",
                "parameters": [
                    {
                        "type": "string",
                        "example": "user-service",
                        "description": "Уникальный идентификатор сервиса",
                        "name": "service_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "service_id и сообщение об успешном удалении",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "service_id is required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "схема с указанным service_id не найдена",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/schema/{service_id}/upload": {
            "post": {
                "description": "Загружает JSON-схему для указанного сервиса через multipart/form-data. Поддерживаются файлы с расширениями .json, .yaml, .yml",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schemas"
                ],
                "summary": "Загрузка JSON-схемы из файла",
                "parameters": [
                    {
                        "type": "string",
                        "example": "user-service",
                        "description": "Уникальный идентификатор сервиса",
                        "name": "service_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "JSON-файл схемы",
                        "name": "schema",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Схема успешно загружена",
                        "schema": {
                            "$ref": "#/definitions/schemaHandler.UploadSchemaResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос: отсутствует service_id, файл слишком большой или неверный формат",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "configHandler.ConfigItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "version": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "configHandler.ConfigListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/configHandler.ConfigItem"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 50
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "service_id": {
                    "type": "string",
                    "example": "user-service"
                },
                "total": {
                    "type": "integer",
                    "example": 15
                }
            }
        },
        "configHandler.ConfigResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "service_id": {
                    "type": "string",
                    "example": "user-service"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-15T15:45:00Z"
                },
                "version": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "configHandler.ConfigVersionResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-14T09:15:00Z"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "service_id": {
                    "type": "string",
                    "example": "user-service"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "configHandler.CreateConfigResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "filename": {
                    "type": "string",
                    "example": "config.json"
                },
                "message": {
                    "type": "string",
                    "example": "config created successfully"
                },
                "service_id": {
                    "type": "string",
                    "example": "user-service"
                },
                "version": {
                    "type": "integer",
                    "example": 7
                }
            }
        },
        "configHandler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "service_id is required"
                }
            }
        },
        "configHandler.RollbackResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "successfully rolled back"
                },
                "rolled_back_at": {
                    "type": "string",
                    "example": "2024-01-15T15:30:00Z"
                },
                "service_id": {
                    "type": "string",
                    "example": "user-service"
                },
                "target_version": {
                    "type": "integer",
                    "example": 3
                },
                "version": {
                    "type": "integer",
                    "example": 8
                }
            }
        },
        "schemaHandler.UploadSchemaResponse": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string",
                    "example": "user-schema.json"
                },
                "message": {
                    "type": "string",
                    "example": "schema uploaded successfully"
                },
                "service_id": {
                    "type": "string",
                    "example": "user-service"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
